language: python

python:
  #- "2.6"
  - "2.7"
  #- "3.2"
  #- "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
  
services:
  - postgresql
  
install:
#  - "sudo apt-get -qq update"
#  - "sudo apt-get install -y postgresql-9.4 postgresql-9.4-postgis-2.2 postgresql-server-dev-all python-psycopg2"
  - "createdb anthill"
  - "psql -U postgres -d anthill -c 'CREATE EXTENSION postgis;'"
  - psql -U postgres -d anthill -c "CREATE USER anthill WITH PASSWORD 'vander';"
  - "'local   all             all                                     md5' >> /etc/postgresql/9.4/main/pg_hba.conf"
  - "/etc/init.d/postgresql reload"
  - "pip install -r requirements.txt"
  - "cp hack4vdb/settings_local.vagrant.py hack4vdb/settings_local.py"

#script: python manage.py test -v 2
