# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 13:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anrede', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('postalcode', models.IntegerField()),
                ('municipal', models.CharField(max_length=500)),
                ('street', models.CharField(max_length=500)),
                ('house_number', models.CharField(max_length=100)),
                ('coordinate', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('datetime', models.DateTimeField()),
                ('postalcode', models.IntegerField()),
                ('municipal', models.CharField(max_length=500)),
                ('street', models.CharField(max_length=500)),
                ('house_number', models.CharField(max_length=100)),
                ('coordinate', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('activist', models.ManyToManyField(to='anthill.Activist')),
            ],
        ),
    ]
