# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('anthill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activist',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='meetup',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
