# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthill', '0003_auto_20160813_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='activist',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='activist',
            name='postalcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='activist',
            field=models.ManyToManyField(blank=True, null=True, related_name='meetups', to='anthill.Activist'),
        ),
    ]
