# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthill', '0005_auto_20160814_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='activist',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
