# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthill', '0006_interestingplaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='activist',
            name='facebook_bot_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
