# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthill', '0008_auto_20160814_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
