# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anthill', '0009_auto_20160814_1636'),
        ('anthill', '0006_activist_last_login'),
    ]

    operations = [
    ]
