# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthill', '0010_merge_20160814_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activist',
            old_name='municipal',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='interestingplaces',
            old_name='municipal',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='meetup',
            old_name='municipal',
            new_name='city',
        ),
        migrations.AddField(
            model_name='activist',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
