# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anthill', '0011_auto_20160815_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='owner',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='anthill.Activist'),
            preserve_default=False,
        ),
    ]
