# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 18:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthill', '0012_meetup_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalcodeCoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postalcode', models.IntegerField()),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('type', models.CharField(max_length=300)),
                ('internal', models.CharField(max_length=300)),
                ('addressable', models.BooleanField()),
                ('mailbox', models.BooleanField()),
                ('coordinate', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('importance', models.FloatField()),
            ],
        ),
    ]
