# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthill', '0013_postalcodecoordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postalcodecoordinates',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='postalcodecoordinates',
            name='importance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postalcodecoordinates',
            name='internal',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='postalcodecoordinates',
            name='state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='postalcodecoordinates',
            name='type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='postalcodecoordinates',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postalcodecoordinates',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
