# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthill', '0014_auto_20160817_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postalcodecoordinates',
            name='postalcode',
            field=models.IntegerField(unique=True),
        ),
    ]
