# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthill', '0017_auto_20160820_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='activists',
            field=models.ManyToManyField(blank=True, related_name='meetups', through='anthill.Participation', to='anthill.Activist'),
        ),
    ]
