# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anthill', '0020_activist_login_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='activist',
            name='invited_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='anthill.Activist'),
        ),
        migrations.AlterField(
            model_name='activist',
            name='login_token',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
