# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthill', '0022_auto_20160820_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailloginjoinmeetupcode',
            name='accessed_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
