# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anthill', '0024_auto_20160820_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activist',
            name='invited_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='anthill.Activist'),
        ),
    ]
