# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthill', '0025_auto_20160821_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='house_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='title',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
